### ISSUE TITLE
make compatible to nesbot/carbon 3.x

### ISSUE THREAD

**Issue by op-euga** [spatie/test-time#15]
Cloud you please make the package compatible to nesbot/carbon 3.x.
I wanted to update my symfony project to 7.0. While nesbot/carbon 3.x is now compatible to symfony 7 it would be great that spatie/test-time is compatible to nesbot/carbon 3.x so that I could update my symfony to version 7.

many thx in advance

**Comment by freekmurze** [comment]
On it now!

**Comment by op-euga** [comment]
Wow that was fast. Many thx again for the very fast update.
