### ISSUE TITLE
More methods support

### ISSUE THREAD

**Issue by MatanYadaev** [spatie/test-time#3]
First, I want to say thank you guys! So simple and helpful package!

I am using this package, and I think it's good to have these methods also:
```php
TestTime::setHour(8); // year, month, day, hour, second, millisecond...
TestTime::hour(8); // Alias of this ^
TestTime::startOfDay(); // startOfYear, startOfMonth...
```

Any other suggestions?

BTW, nice implementation, you guys rock it.

**Comment by freekmurze** [comment]
Glad that you like this package.

You can already use these methods. Your problem is probably that you don't get autocompletion. Feel free a PR with more docblocks 👍

**Comment by MatanYadaev** [comment]
Yea, I already use these methods, I will be glad to create a PR. Thanks!
